## COMP3670 Programming Assignment 1 - Linear Algebra
---

**Enter Your Student ID:** u7540836

**Your Name:** Nanthawat Anancharoenpakorn
    
**Deadline:** 

**Submit:** Write your answers in this file, and submit a single Jupyter Notebook file (.ipynb) on Wattle. Rename this file with your student number as 'uXXXXXXX.ipynb'.

**Enter Discussion Partner IDs Below:**
You could add more IDs with the same markdown format above.



---
**Marking distribution for the assignment**

- Task1 = 10%
- Task2 = 50%
- Task3 = 40%

**You will get full marks if your program passes all the tests; you will get partial marks if it passes some cases. There is no process marks (we do not look into your codes).**

## Task 0: Introduction
---

**NOTE:** *This part of the first assignment is by necessity somewhat tedious as its primary purpose is to introduce syntax, how to access and understand the Numpy documentation and some very basic concepts. If you are already familiar with Numpy, you can just read the **TASK** headings and complete the questions without worrying about all the additional information. This is designed for people who have never seen Numpy before, so it's a very easy 1st year style introduction to just introduce syntax.*

*As this is a third year subject, it is assumed you already know to to program well (but may be unfamiliar with Python and Numpy).*

---

Arguably the most fundamental tool needed to engage with machine learning in Python is Numpy *(np)*. To include Numpy in any project, simply type the following line at the top of your python file:

In [1]:
# numpy
import numpy as np

!pip install sympy
import sympy as sp

# matplotlib
import matplotlib.pyplot as plt
%matplotlib inline

A Jupyter Notebook is divided into cells, each of which works like a Python module or Latex file. When a cell is run, any cells that follow it will have access to its results. Running the above cell will give all following cells access to the Numpy library.

-----------

   **TASK 0.1:** To run the above cell, select it by clicking on it, hold **shift** and press **return**. If you have succeeded, then the cell will print "Done" just above.


-----------

Numpy is a library of common mathematical data structures and algorithms used in machine learning. For example:

- It allows you to declare vectors and matrices, with all the associated mathematical operations like matrix vector products, matrix addition / subtraction.
- It provides convenient, efficient implementations of algorithms to solve matrix equations, find the inverse of a matrix or perform Eigen decomposition. The implementation of these algorithms is compiled from C code, making Numpy much faster than programming these algorithms yourself in Python.

You'll need to know Numpy inside and out. We'll start by getting you familiar with the easy to access online documentation and performing a few basic operations.

Below I have declared the matrices: 

$$A = 
\begin{bmatrix}
2&3\\
0&1\\
\end{bmatrix}
\\
x = 
\begin{bmatrix}
1\\
3\\
\end{bmatrix}
$$. 

---
**TASK 0.2:** Run the cell below and observe what it prints.


---
(If it throws an error, you have the wrong version of python installed. This entire course will use Python 3, not Python 2)



In [2]:
A = np.array([[2, 3], [0, 1]])
x = np.array([[1], [3]])

#Matrix Multiplication Example
b = A @ x
print('\nMatrix Multiplication')
print(b)


Matrix Multiplication
[[11]
 [ 3]]


The above code illustrates how to perform matrix multiplication. Memorise it. Below are some other basic operations you'll likely need over the coming semester:

In [3]:
# Data
print("\nMatrix A")
print(A)
print("\nMatrix x")
print(x)


#Matrix Addition Example
b = A + x
print('\nMatrix Addition')
print(b)

#Elementwise Multiplication Example
b = A * x
print('\nElementwise Matrix Multiplication')
print(b)

#Extract a single element of a matrix:
print('\nSingle Element Extraction')
b = A[0, 0]
print(b)
print(A[0,1]) # A 0,1
#Extract an entire column of a matrix:
print('\nColumn Extraction')
b = A[:, 0]
print(b)
print(A[:,1])

#Extract an entire row of a matrix:
print('\nRow Extraction')
b = A[0, :]
print(b)

#Transpose of a matrix:
print('\nTranspose')
A_Transpose = A.T
print(A_Transpose)


Matrix A
[[2 3]
 [0 1]]

Matrix x
[[1]
 [3]]

Matrix Addition
[[3 4]
 [3 4]]

Elementwise Matrix Multiplication
[[2 3]
 [0 3]]

Single Element Extraction
2
3

Column Extraction
[2 0]
[3 1]

Row Extraction
[2 3]

Transpose
[[2 0]
 [3 1]]


## Task1: Solving a system of linear equations
---

A vital part of linear algebra is to know how to solve a system of linear equations. For e.g. 

$$a_{11}x_1+a_{12}x_2 \dots a_{1d}x_d=b_1$$
$$a_{21}x_1+a_{22}x_2 \dots a_{2d}x_d=b_2$$
$$\vdots$$
$$a_{n1}x_1+a_{n2}x_2 \dots a_{nd}x_d=b_n$$

The above system of linear equations can also be written down in a compact matrix form as follows:

$$AX = B$$

where,
$$A = \begin{bmatrix}
a_{11} & \dots & a_{1d}\\
\vdots & \ddots & \vdots \\
a_{n1} & \dots & a_{nd}
\end{bmatrix}, \quad
B = \begin{bmatrix}
b_1 \\ \vdots \\ b_n
\end{bmatrix}, \quad
X = \begin{bmatrix}
x_1 \\ \vdots \\ x_d
\end{bmatrix}.
$$

---
**Task 1.1**: Use numpy's solve function to compute X

---
**HINT**: https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.solve.html

In [4]:
# Task 1.1 Model

a = np.array([[1,2],[3,5]])
b = np.array([1,2])
x = np.linalg.solve(a,b)


In [5]:
# define A,B
A = np.array([[10, 14, 4], [15, 2, 6], [7, 8, 18]])
B = np.array([[2], [1], [2]])

def solve_with_numpy(A,B):
    # TODO: solve the linear system
    X = np.linalg.solve(A,B)
    return(X)

# show solution
X = solve_with_numpy(A,B)
print (X)

[[0.03185596]
 [0.10526316]
 [0.05193906]]


A more hands on way for solving for X, involves computing first computing the inverse of the matrix $A$

---
**Task 1.2**: Use numpy's inbuilt method for computing the inverse of the matrix $A$

---

**HINT**: https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html

In [6]:
A = np.array([[7, 1], [15, 4]])

def find_inverse(A):
    
    # TODO: find the inverse of the matrix A
    return np.linalg.inv(A)
    
A_inv = find_inverse(A)
print(A_inv)

[[ 0.30769231 -0.07692308]
 [-1.15384615  0.53846154]]


---
**Task 1.3**: Use the inverse of matrix $A$, to solve for $X$. **Note that you are only allowed to use the functions in 1.1 and 1.2. No other library functions are allowed**.

---

In [7]:
# Task 1.3 Model 
# find  X from AX = B by (A_inverse @  B = X)

In [8]:
A = np.array([[5, 3], [2, 11]])
B = np.array([[16], [5]])

def solve_with_prev_tasks(A, B):
    # TODO: solve the linear system using functions you have written
    X = find_inverse(A) @ B
    return X

X = solve_with_prev_tasks(A, B)
print(X)

[[ 3.28571429]
 [-0.14285714]]


But what if $A$ is not a square matrix?

---
**Task 1.4**: Compute the Moore-Penrose pseudo inverse for matrix $A$ and **use it to solve for $x$**. **Note that, you must not directly use `np.linalg.pinv` for computing the pseudo-inverse**.

---



In [9]:
# A @ X_hat = b where X_hat = A_+ @ B

In [10]:
A = np.array([[15, 1], [5, 10], [8, 2], [11, 19]])
B = np.array([[18], [15], [2], [8]])

def pseudo_inverse(A):
    # Compute the pseudo-inverse of a matrix
    pseudo_inv = np.linalg.inv(A.T @ A) @ A.T
    return pseudo_inv

def solve_with_pseudo_inverse(A, B):
    A_pseudo = pseudo_inverse(A)
    # Solve for x using pseudo-inverse method
    X = A_pseudo @ B
    return X 


X = solve_with_pseudo_inverse(A, B)
print(X)

[[0.97187421]
 [0.09046455]]


## Task 2: Solving a system of linear equations with Gaussian elimination

In the last task, we used numpy's inbulit functions to solve a system of linear equations. Lets do it without using these functions!

---
**Task 2.1**:  Complete the following gaussian elimnation function to compute the **reduced row-echelon form** of matrix $A$. You must implement the gaussian elimination algorithm yourself, not merely call someone else's library function. You **MUST NOT** copy codes from any source. Your function needs to work under **different shapes** of matrix. Negative zero is a result of the floating-point number standard. If you have some -0s instead of 0s, that should be fine.

---

In [131]:
def gaussian_elim(X):
    # Convert the input matrix to float64
    A = np.array(X, dtype=np.float64)
    
    rows, cols = A.shape
    for c in range(cols):
        # Find the pivot row
        pivot_row = None
        for r in range(c, rows):
            if A[r, c] != 0:
                pivot_row = r
                break

        # If no pivot found, continue to next column
        if pivot_row is None:
            continue

        # Swap pivot row with current row
        A[[c, pivot_row]] = A[[pivot_row, c]]

        # Normalize pivot row
        A[c] = A[c] / A[c, c]

        # Eliminate other rows
        for r in range(rows):
            if r != c:
                A[r] = A[r] - A[r, c] * A[c]

    # Handle negative zeros
    A[A == -0] = 0

    return A

In [132]:
A = np.array([[18, 18, 14, 15, 14, 19,  8,  7,  2, 11],
               [ 3,  7,  8,  8,  2,  2,  8, 17,  6,  8],
               [ 2,  8,  6,  4, 11, 10, 15, 11, 12,  3],
               [ 9,  4, 17,  6,  6, 12, 13,  0, 12,  2],
               [ 0,  3, 18,  0, 13,  6,  8, 13, 16, 15],
               [15, 16, 13,  9,  4, 17, 11,  0,  5, 18],
               [10,  4,  6, 12,  6, 18, 17,  7,  5,  6],
               [ 3, 12,  2,  4, 16,  1, 17,  8, 10,  2],
               [ 7,  8, 11,  4, 12, 14, 18, 14,  9, 16],
               [18, 13,  3, 19, 16,  9,  6,  8,  2, 15]])

print(gaussian_elim(A))

# The result should be an identity matrix

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [133]:
B = np.array([[ 5,  3, 14,  1,  2, 15,  1, 11],
               [ 3, 13,  5, 18, 16, 18, 12,  4],
               [ 1,  9, 12, 15, 15,  0,  7,  0],
               [18, 17,  5,  0, 11,  4, 17,  9]])

print(gaussian_elim(B))
# The result should look like
# [[  1.           0.           0.           0.          -2.77442593 20.86492571  -0.07248987   7.64520486]
#  [  0.           1.           0.           0.           3.44146781 -21.02183701   1.11661414  -7.36402521]
#  [  0.           0.           1.           0.           0.48694282 -2.83948672  -0.13552454  -0.68505178]
#  [  0.           0.           0.           1.          -1.26947321 13.49369653  -0.09004953   4.45677623]]

[[  1.           0.           0.           0.          -2.77442593
   20.86492571  -0.07248987   7.64520486]
 [  0.           1.           0.           0.           3.44146781
  -21.02183701   1.11661414  -7.36402521]
 [  0.           0.           1.           0.           0.48694282
   -2.83948672  -0.13552454  -0.68505178]
 [  0.           0.           0.           1.          -1.26947321
   13.49369653  -0.09004953   4.45677623]]


In [134]:
C = np.array([[ 3, 12, 17],
               [14, 19,  8],
               [ 1, 12,  7],
               [10, 17, 11],
               [ 6,  0, 12],
               [16,  3, 15],
               [16, 19, 18]])

print(gaussian_elim(C))
# The result should look like
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]
#  [0. 0. 0.]
#  [0. 0. 0.]
#  [0. 0. 0.]
#  [0. 0. 0.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Make sure you pass the following test. Note that, passing the test set does not guarantee you with full mark. We will use different cases when testing your implementation.

In [135]:
# test your gaussian_elim function
def test_gaussian_elim():
    for i in range(100):
        m, n = np.random.randint(low=5, high=10, size=2)
        a = np.random.randn(m, n)
        sol1 = gaussian_elim(a)
        sol2 = np.array(sp.Matrix(a).rref()[0])
        if np.sum((sol1 - sol2) ** 2) > 1e-6:
            print(a, "\n")
            print(gaussian_elim(a), "\n")
            print(np.array(sp.Matrix(a).rref()[0]), "\n")
            return False
    test_cases = [np.array([[2, 0, 1, 1],
                            [2, 0, 1, 1],
                            [0, 0, 0, 0],
                            [1, 1, 1, 0]], dtype=np.float64),
                  np.array([[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9]], dtype=np.float64),
                  ]
    for test in test_cases:
        sol1 = gaussian_elim(test)
        sol2 = np.array(sp.Matrix(test).rref()[0])
        if np.sum((sol1 - sol2) ** 2) > 1e-6:
            print(test, "\n")
            print(gaussian_elim(test), "\n")
            print(np.array(sp.Matrix(test).rref()[0]), "\n")
            return False
    return True
test_gaussian_elim()

True

---
**Task 2.2**: A system of linear equations is called homogeneous if the right hand side is the zero vector. Sometimes there will be only trivial solution, namely the zero vector. An example of this matrix is:
$$2x_1+4x_2 =0$$
$$2x_1+5x_2 =0$$
Sometimes there will be non-trivial solutions, e.g.,
$$2x_1+4x_2 =0$$
$$1x_1+2x_2 =0$$
The solution can be $x_1 =-2$, $x_2 =1$.
 
$A=\big(\begin{smallmatrix}
  2 & 4\\
  1 & 2
\end{smallmatrix}\big)$ is called coefficient matrix.
Your task is solving a homogeneous system of linear equations based on its reduced row-echelon form, i.e., the output of your *gaussian_elim* function in Task 2.1. You **MUST NOT** revoke any numpy inbuilt functions you used in Task 1. Your function needs to work under **different shapes** of $A$. 

The *solve_homogeneous* function should be according to the following specifications:
* Take as input the coefficient matrix $A$. 
* Return:
    - 0 if it only has trivial solution. Type: int.
    - otherwise, return any two different non-trivial solutions. Type: tuple((np.ndarray, Type: np.ndarray)).  Note that the dimensions of the np.ndarray should be 1, i.e., using one pair of square brackets. See demo outputs below.

In [136]:
def solve_homogeneous(A):
    
    # Convert to identity
    A = gaussian_elim(A)
    rows, cols = A.shape
    
    # Check for full rank
    full_rank = np.linalg.matrix_rank(A) == rows

    # Check for rows of all zeros
    has_zero_row = any(np.all(row == 0) for row in A)

    # If the matrix has full rank and no rows of all zeros, only the trivial solution exists
    if full_rank and not has_zero_row:
        return int(0)
    
    else:
        # check if it is Identity
        isIdentity = True
        for col in range(A.shape[1]):
            for row in range(A.shape[0]):
                if(col == row):
                    if(A[row,col] != 1):
                        isIdentity = False
                else:
                    if(A[row,col] != 0):
                        isIdentity = False

        if(isIdentity):
            return int(0)

        else:
             # Find a non-trivial solution by setting free variables
            solution1 = np.zeros(cols)
            solution2 = np.zeros(cols)

            # Set values for free variables and compute corresponding dependent variables
            for i in range(cols):
                if i < rows and A[i, i] == 1:
                    continue  # Skip pivot variables
                solution1[i] = 1
                solution2[i] = 2
                for j in range(rows):
                    solution1[j] -= A[j, i]
                    solution2[j] -= 2 * A[j, i]

            return (solution1[np.newaxis, :], solution2[np.newaxis, :])


In [137]:
A = np.array([[ 6,  9,  1,  7],
               [17,  1,  3, 17],
               [ 8,  4,  9, 13],
               [18,  4, 18, 18]])
print(solve_homogeneous(A))
# The result should look like
# 0

0


In [138]:
B = np.array([[ 6,  8,  6, 15, 12],
           [17,  8,  8, 12,  2],
           [18, 15, 15,  7,  2],
           [ 7,  6, 10,  3, 18],
           [14,  4,  4,  2, 16]])
print(solve_homogeneous(B))
# The result should look like
# 0

0


In [139]:
C = np.array([[ 8, 18, 18],
               [14, 19, 15],
               [4,  9,  9]])

print(solve_homogeneous(C))
# The result should look like
# (array([ 0.72, -1.32,  1.  ]), array([ 1.44, -2.64,  2.  ]))
# Note they are not unique

(array([[ 0.72, -1.32,  1.  ]]), array([[ 1.44, -2.64,  2.  ]]))


In [140]:
D = np.array([[10,  3,  2,  8],
           [16,  5,  8,  5],
           [ 0,  0, 13, 16]])

print(solve_homogeneous(D))
#The result should look like
# ((array([-21.11538462,  68.53846154,  -1.23076923,   1.        ]), 
# array([-42.23076923, 137.07692308,  -2.46153846,   2.        ]))
# Note they are not unique

0


In [141]:
E = np.array([[ 2, 12,  2],
           [12,  8,  7],
           [14,  5, 17],
           [ 8, 10,  5]])

print(solve_homogeneous(E))
# The result should look like
# 0

0


Make sure you pass the following test. Note that, passing the test set does not guarantee you with full mark. We will use different cases when testing your implementation.

In [142]:
def test_homogeneous_trivial():
    # test A with m>n and m=n but no dependent rows in it
    for i in range(1000):
        m = np.random.randint(low=4, high=6)
        n = np.random.randint(low=2, high=5)
        a = np.random.randn(m, n)
        res = solve_homogeneous(a)
        if res != 0:
            print(a, '\n')
            print(f' solution should be 0 but got {res}')
            return False
    # test A with m>n and there are dependent rows in it
    test_list = [
        np.array([[1, 2], [3, 4], [2, 4]]),
        np.array([[1, 2, 3], [2, 4, 6], [3, 4, 5], [4, 7, 9]]),
    ]
    for case in test_list:
        res = solve_homogeneous(case)
        if res != 0:
            print(a, '\n')
            print(f' solution should be 0 but got {res}')
            return False
    return True

def test_homogeneous_nontrivial():
    import random
    # test A with m=n and m<n
    for i in range(1000):
        m = np.random.randint(low=2, high=5)
        n = np.random.randint(low=4, high=6)
        a = np.random.randn(m, n)
        a_ = a.copy()
        # create matrices whose rows or columns are dependent
        dpdt = random.sample(range(0, m), np.random.randint(low=2, high=m + 1))
        duplicate = a[dpdt[0]]
        for row in dpdt:
            a[row] = duplicate
        x1 = np.expand_dims(solve_homogeneous(a)[0], axis=1)
        x2 = np.expand_dims(solve_homogeneous(a)[1], axis=1)
        if abs(np.sum(a @ x1)) > 1e-6 or abs(np.sum(a @ x2)) > 1e-6 or (x1==x2).all():
            print(a_, '\n')
            print('the solutions are not correct')
            return False
    # test A with m>n
    test_list = [
        np.array([[1, 2], [1, 2], [2, 4]]),
        np.array([[1, 2, 3], [3, 6, 9], [1, 2, 3], [4, 7, 9]]),
        np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    ]
    for case in test_list:
        x1 = np.expand_dims(solve_homogeneous(case)[0], axis=1)
        x2 = np.expand_dims(solve_homogeneous(case)[1], axis=1)
        if abs(np.sum(case @ x1)) > 1e-6 or abs(np.sum(case @ x2)) > 1e-6 or (x1==x2).all():
            print(a_, '\n')
            print('the solutions are not correct')
            return False
    return True

print(test_homogeneous_trivial())
print(test_homogeneous_nontrivial())

True


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 5)

---
**Task 2.3**: A system of linear equations is called non-homogeneous if the right hand side is not the zero vector. A non-homogeneous system of linear equations has
* no solution, or
* a unique solution, or
* infinite number of solutions

Similar to Task 2.2, your task is solving a non-homogeneous system of linear equations. You **MUST NOT** revoke any numpy inbuilt functions you used in Task 1, however, you are allowed to use the functions you defined in Task 2.2. Your function needs to work under **different shapes** of augmented matrix $[A|b]$. 

The *solve_nonhomogeneous* function should be according to following specifications:
* Take as input the augmented matrix $[A|b]$. 
* Return:
    - None if it has no solution at all. Type: None.
    - the single solution if it only has one solution. Type: np.ndarray.
    - otherwise, return any two different solutions if it has more than one solutions. Type: tuple((np.ndarray, Type: np.ndarray)).
*  Note that the dimensions of the np.ndarray should be 1, especially, one pair of square brackets. See demo outputs below.    

In [143]:
# Define the coefficients of the system of equations
A = np.array([[9, 19, 2],
              [5, 7, 3],
              [14, 6, 1]])

# Define the constants
b = np.array([[18],
              [14],
              [9]])

# Combine A and b to form the augmented matrix Ab
Ab = np.hstack((A, b))

# Call the function with the augmented matrix
result = solve_nonhomogeneous(Ab)

# Print the result
print(result)

[[0.19444444 0.52777778 3.11111111]]


In [154]:
def solve_nonhomogeneous(Ab):
    # Convert to RREF using Gaussian elimination
    RREF = gaussian_elim(Ab)
    rows, cols = RREF.shape
    cols -= 1  # Exclude the last column for b

    # Check for no solution
    if any(all(row[:-1] == 0) and row[-1] != 0 for row in RREF):
        return None

    # Check for unique solution
    pivot_columns = sum(1 for row in RREF if any(row[:-1]))
    if pivot_columns == rows:
        solution = np.zeros(cols)
        for i in range(rows):
            solution[i] = RREF[i, -1] - sum(RREF[i, j] * solution[j] for j in range(i + 1, cols))
        return solution[np.newaxis, :]

    # Check for infinite solutions
    solution1 = np.zeros(cols)
    solution2 = np.zeros(cols)
    for i in range(rows):
        if RREF[i, i] == 1:
            solution1[i] = RREF[i, -1] - sum(RREF[i, j] * solution1[j] for j in range(i + 1, cols))
            solution2[i] = RREF[i, -1] - sum(RREF[i, j] * solution2[j] for j in range(i + 1, cols))
        else:
            # Set values for free variables
            free_var_index = next((j for j in range(cols) if RREF[i, j] != 0), None)
            if free_var_index is not None:
                solution1[free_var_index] = 1
                solution2[free_var_index] = 2

    return (solution1[np.newaxis, :], solution2[np.newaxis, :])

# Example usage
B = np.array([[ 9, 19,  2, 18],
           [ 5,  7,  3, 14],
           [14,  6,  1,  9]])


print(solve_nonhomogeneous(B))

[[0.19444444 0.52777778 3.11111111]]


In [155]:
A = np.array([[ 9,  5, 14,  3],
           [ 9,  1, 11,  0],
           [ 0,  4,  3,  2]])

print(solve_nonhomogeneous(A))
# The result should look like
# None

None


In [156]:
B = np.array([[ 9, 19,  2, 18],
           [ 5,  7,  3, 14],
           [14,  6,  1,  9]])

print(solve_nonhomogeneous(B))
# The result should look like
# [0.19444444 0.52777778 3.11111111]

[[0.19444444 0.52777778 3.11111111]]


In [157]:
C = np.array([[14, 14,  0, 18,  2, 11],
           [12, 12,  5,  1, 19, 13],
           [ 9,  3,  7,  1,  2, 11],
           [18, 10,  6, 12,  8, 16]])
print(solve_nonhomogeneous(C))
# The result should look like
# (array([-2.99214286,  0.35642857,  4.61571429,  2.55      ,  1.        ]), 
# array([-6.15785714,  0.29357143,  8.08428571,  4.95      ,  2.        ]))
# The results are not unique

[[0.17357143 0.41928571 1.14714286 0.15       0.        ]]


Make sure you pass the following test. Note that, passing the test set does not guarantee you with full mark. We will use different cases when testing your implementation.

In [158]:
def test_nonhomogeneous_no_solution():
    import random
    for i in range(1000):
        m = np.random.randint(low=3, high=6)
        n = np.random.randint(low=3, high=6)
        a = np.random.randn(m, n)
        a_ = a.copy()
        # create matrices whose rows conflict
        cflt = random.sample(range(0, m), np.random.randint(low=2, high=m + 1))
        duplicate = a[cflt[0]]
        for row in cflt:
            a[row] = duplicate
            a[row][-1] = np.random.normal(loc=a[row][-1])
        if solve_nonhomogeneous(a):
            print(a_, '\n')
            print(f'the solution should be None, but got {solve_nonhomogeneous(a)}')
            return False
    return True

def test_nonhomogeneous_single_solution():
    # test square A
    for i in range(1000):
        m = np.random.randint(low=3, high=6)
        n = m + 1
        a = np.random.randn(m, n)
        x = np.expand_dims(solve_nonhomogeneous(a), axis=1)
        if abs(np.sum(a[:, :-1] @ x) - np.sum(a[:, -1])) > 1e-6:
            print(a, '\n')
            print('the solution is not correct')
            return False
    test_list = [
        np.array([[1, 1, 1], [1, 3, 3], [2, 2, 2]]),
        np.array([[1, 2, 3, 2], [2, 4, 6, 4], [3, 6, 9, 6], [4, 7, 9, 10], [1, 2, 4, 7]]),
    ]
    # test A with m>n
    for case in test_list:
        x = np.expand_dims(solve_nonhomogeneous(case), axis=1)
        if abs(np.sum(case[:, :-1] @ x) - np.sum(case[:, -1])) > 1e-6:
            print(a, '\n')
            print('the solution is not correct')
            return False
    return True

def test_nonhomogeneous_infinite_solution():
    import random
    for i in range(1000):
        # test A with m=n and m<n whose rows are dependent
        m = np.random.randint(low=2, high=5)
        n = m + np.random.randint(low=1, high=4)
        a = np.random.randn(m, n)
        a_ = a.copy()
        # create matrices whose rows or columns are dependent
        dpdt = random.sample(range(0, m), np.random.randint(low=2, high=m + 1))
        duplicate = a[dpdt[0]]
        for row in dpdt:
            a[row] = duplicate
        x1 = np.expand_dims(solve_nonhomogeneous(a)[0], axis=1)
        x2 = np.expand_dims(solve_nonhomogeneous(a)[1], axis=1)
        if abs(np.sum(a[:, :-1] @ x1) - np.sum(a[:, -1])) > 1e-6 or abs(
                np.sum(a[:, :-1] @ x2) - np.sum(a[:, -1])) > 1e-6 or (x1==x2).all():
            print(a_, '\n')
            print('the solutions are not correct')
            return False
        # test A with m<n whose rows are not dependent
        if n > m + 1:
            x1 = np.expand_dims(solve_nonhomogeneous(a_)[0], axis=1)
            x2 = np.expand_dims(solve_nonhomogeneous(a_)[1], axis=1)
            if abs(np.sum(a[:, :-1] @ x1) - np.sum(a[:, -1])) > 1e-6 or abs(
                    np.sum(a[:, :-1] @ x2) - np.sum(a[:, -1])) > 1e-6 or (x1==x2).all():
                print(a_, '\n')
                print('the solutions are not correct')
                return False
    # test A with m>n whose rows are dependent
    test_list = [
        np.array([[1, 2, 3], [2, 4, 6], [3, 6, 9]]),
        np.array([[1, 2, 3, 4], [2, 4, 6, 8], [1, 4, 7, 9], [1, 2, 3, 4], [2, 4, 6, 8]]),
    ]
    for case in test_list:
        x1 = np.expand_dims(solve_nonhomogeneous(case)[0], axis=1)
        x2 = np.expand_dims(solve_nonhomogeneous(case)[1], axis=1)
        if abs(np.sum(case[:, :-1] @ x1) - np.sum(case[:, -1])) > 1e-6 or abs(
                np.sum(case[:, :-1] @ x2) - np.sum(case[:, -1])) > 1e-6 or (x1==x2).all():
            print(case, '\n')
            print('the solutions are not correct')
            return False
    return True

print(test_nonhomogeneous_no_solution())
print(test_nonhomogeneous_single_solution())
print(test_nonhomogeneous_infinite_solution())

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

## Task 3: Rank, Basis and Span

Given a matrix $X$, would it be possible for you to programmably determine its rank, null space and column space? In this question, you are tasked at **1) finding the rank and the dimension of the null space $X$, 2) finding the basis that spans the column space of $X$, and 3) finding the basis that spans the null space of $X$.**

---
**Task 3.1**: Implement two functions `rank`, `dim_null`.

`rank`: takes arbitrary matrix $X$ as input, output its rank.

`dim_null`: takes arbitrary matrix $X$ as input, output the dimension of its null space

**Note: If you didn't get Gaussian Elimination in task2, you may use the library function `sp.Matrix(X).rref()` to get the reduced row echelon form of $X$. But, you must not use other library functions that can solve questions directly.**

In [37]:
# Working space
def rank(A):
    # Get the RREF of A using Gaussian elimination
    rref_matrix = gaussian_elim(A)
    
    # Count the number of non-zero rows
    rank = sum(1 for row in rref_matrix if any(row))
    
    return rank

def dim_null(A):
    # Get the rank of A
    rank_A = rank(A)
    
    # Get the number of columns
    cols = len(A[0])
    
    # The dimension of the null space is the difference between the number of columns and the rank
    return cols - rank_A


In [38]:
# Working space
A = np.array([[ 1,  8,  4],
               [ 0,  0, 11],
               [15,  2, 11],
               [12,  0,  3]])

print(gaussian_elim(A))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [39]:
A = np.array([[0, 0, 0], 
              [0, 0, 0], 
              [0, 0, 0]])

print(rank(A))
print(dim_null(A))

# you should get
# 0
# 3

0
3


In [40]:
B = np.array([[16,  8, 12,  8,  5],
               [ 0,  7,  9, 14,  2],
               [14, 12, 13, 15, 14],
               [13, 18, 16, 19, 12]])

print(rank(B))
print(dim_null(B))

# you should get
# 4
# 1

4
1


In [41]:
C = np.array([[ 1,  8,  4],
               [ 0,  0, 11],
               [15,  2, 11],
               [12,  0,  3]])

print(rank(C))
print(dim_null(C))

# you should get
# 3
# 0

3
0


Make sure you pass the following test. Here we only provide the test for the rank.

In [102]:
def test_rank():
    for _ in range(1000):
        rnd_h = np.random.randint(1, 10)
        rnd_w = np.random.randint(1, 10)
        rnd_mat = np.random.choice(100, [rnd_h, rnd_w], replace=True).astype(np.float64)
        if rank(rnd_mat) != np.linalg.matrix_rank(rnd_mat):
            return False
    return True
test_rank()

True



---
**Task 3.2**: Implement `basis_col`.

`basis_col`: takes arbitrary matrix $X$ as input, output a basis that spans the column space of $X$. The basis should be a numpy array or a list, containing several numpy array vectors. 

---

In [101]:
# Workiing space


def basis_col(A):
    # Convert to RREF to identify linearly independent columns
    RREF = gaussian_elim(A)
    
    # Identify the linearly independent columns
    basis = []
    for i in range(RREF.shape[1]):
        if any(RREF[:, i] != 0):
            basis.append(A[:, i])
    
    # If no linearly independent columns found, return a single zero vector
    if not basis:
        return np.zeros((A.shape[0], 1))
    
    return np.array(basis).T # np.column_stack(basis)

In [98]:
A = np.array([[0, 0, 0], 
              [0, 0, 0], 
              [0, 0, 0]])

print(basis_col(A))

# should return 
# array([[0], [0], [0]])

[[0.]
 [0.]
 [0.]]


In [99]:
B = np.array([[13, 11,  6,  9,  6],
            [ 0, 12, 16, 11, 14],
            [ 5, 15,  8,  3,  0],
            [16,  3,  1, 14,  5]])

print(basis_col(B))

# should return something like
# array([[13, 11, 6, 9], [0, 12, 16, 11], [5, 15, 8, 3], [16, 3, 1, 14]])
# the solution is not unique

[[13 11  6  9  6]
 [ 0 12 16 11 14]
 [ 5 15  8  3  0]
 [16  3  1 14  5]]


In [100]:
C = np.array([[1, 1], 
              [1, 1], 
              [1, 1]])

print(basis_col(C))
# should return something like
# array([[1], [1], [1]])
# the solution is not unique

[[1 1]
 [1 1]
 [1 1]]


We will use more test cases when testing your implementation.

---
**Task 3.3**: Implement `basis_null`.

`basis_null`: takes arbitrary matrix $X$ as input, output a basis that spans the null space of $X$. The basis should be a numpy array or a list, containing several numpy array vectors.

---

In [67]:
# Working environment

def basis_null(A):
    # Convert to RREF to identify free variables
    RREF = gaussian_elim(A)
    rows, cols = RREF.shape
    basis = []
    
    # Identify pivot columns (columns with leading 1s)
    pivot_columns = [np.argmax(row) if any(row) else None for row in RREF]
    
    # Iterate through columns to find free variables
    for i in range(cols):
        if i not in pivot_columns:
            vector = np.zeros(cols)
            vector[i] = 1
            
            for r in range(rows):
                pivot_col = pivot_columns[r]
                if pivot_col is not None and pivot_col < cols:
                    vector[r] = -RREF[r, i]
            
            basis.append(vector)
    
    return np.array(basis).T

In [68]:
A = np.array([[0, 0, 0], 
              [0, 0, 0], 
              [0, 0, 0]])

print(basis_null(A))

# should return something like an identity matrix. The solution is not unique.

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [69]:
B = np.array([[16, 16, 11],
            [14, 19, 11],
            [11, 12, 19]])

print(basis_null(B))

# should return
# array([[0], [0], [0]])

[]


We will use more test cases when testing your implementation.